// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQlbZbAtT6vTCY191Qlh0axLmcWSds05s',
    appId: '1:1046204540356:web:1af2be11bc20a4ab82f091',
    messagingSenderId: '1046204540356',
    projectId: 'app-homero-flutter',
    authDomain: 'app-homero-flutter.firebaseapp.com',
    storageBucket: 'app-homero-flutter.firebasestorage.app',
    measurementId: 'G-YG5MQYHF3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmN2GfPw3MtQQ0simtxiBZXekpEmNXeWc',
    appId: '1:1046204540356:android:977ea8692a56ddce82f091',
    messagingSenderId: '1046204540356',
    projectId: 'app-homero-flutter',
    storageBucket: 'app-homero-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnlMa6AARAt1A375b7oXRjGkBF1kScwwg',
    appId: '1:1046204540356:ios:33825262b27181bf82f091',
    messagingSenderId: '1046204540356',
    projectId: 'app-homero-flutter',
    storageBucket: 'app-homero-flutter.firebasestorage.app',
    iosBundleId: 'com.example.proyectoHomero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnlMa6AARAt1A375b7oXRjGkBF1kScwwg',
    appId: '1:1046204540356:ios:33825262b27181bf82f091',
    messagingSenderId: '1046204540356',
    projectId: 'app-homero-flutter',
    storageBucket: 'app-homero-flutter.firebasestorage.app',
    iosBundleId: 'com.example.proyectoHomero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQlbZbAtT6vTCY191Qlh0axLmcWSds05s',
    appId: '1:1046204540356:web:8f8e5a64ad7ef7f682f091',
    messagingSenderId: '1046204540356',
    projectId: 'app-homero-flutter',
    authDomain: 'app-homero-flutter.firebaseapp.com',
    storageBucket: 'app-homero-flutter.firebasestorage.app',
    measurementId: 'G-V1M1RVKSJH',
  );
}
